// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA07GZeMLpdVkFapLfOADj4BLJVxY66XMY',
    appId: '1:579438374253:android:eda36bfb42d7bb42977e64',
    messagingSenderId: '579438374253',
    projectId: 'udemy-flutter-chat-app-f07a5',
    storageBucket: 'udemy-flutter-chat-app-f07a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASdaevQpqtc5kGyFT_P1rQHOuzZJsjLCA',
    appId: '1:579438374253:ios:b4e746b47f0f3f67977e64',
    messagingSenderId: '579438374253',
    projectId: 'udemy-flutter-chat-app-f07a5',
    storageBucket: 'udemy-flutter-chat-app-f07a5.firebasestorage.app',
    iosClientId: '579438374253-q65t7df3b5q4qjp27cfe8u1ahlijrigd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotification1',
  );

}